<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="System.Data.SQLite.Core" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <ProjectReference Include="..\AiAssistant.Storage\AiAssistant.Storage.csproj" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
  </ItemGroup>

</Project>
