<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.Ollama" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="System.ClientModel" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AiAssistant.Core\AiAssistant.Core.csproj" />
  </ItemGroup>
</Project>
